/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Java_com_actor_cpptest_ConstUtils */

#ifndef _Included_com_actor_cpptest_ConstUtils
#define _Included_com_actor_cpptest_ConstUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actor_cpptest_ConstUtils
 * Method:    jniInit
 * Signature: (Landroid/content/Context;Z)V
 */
JNIEXPORT void JNICALL
Java_com_actor_cpptest_ConstUtils_jniInit(JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_actor_cpptest_ConstUtils
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_actor_cpptest_ConstUtils_getString(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
